### ISSUE TITLE
Make "C" plug WBO / aux connector

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#1]
https://github.com/rusefi/rusefi/wiki/OEM-connectors#125

353028-1
https://www.findchips.com/search/353028-1

terminals
https://www.findchips.com/search/175180

available new
![image](https://user-images.githubusercontent.com/48498823/205784853-36a88147-eecd-4343-94a6-e5b7e574a423.png)

**Comment by rusefillc** [comment]
used pigtail 16 pins

![image](https://user-images.githubusercontent.com/48498823/205787083-596ff3cf-a8fc-4bd1-bc6c-67ec85bc3cea.png)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/213298023-797fd70e-b2f2-41c1-a859-e81714c8fe9d.png)
