### ISSUE TITLE
blue "ALTC"

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#12]
we need blue "ALTC" note next to B18 since that's the standard convention

![image](https://user-images.githubusercontent.com/48498823/211668125-7c397ab2-f5d0-4ad9-b90e-c1e3cbf78fc8.png)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/211922139-a0822928-5318-4473-9892-8eda00fe5bc6.png)
