### ISSUE TITLE
B21 evap should be aux low side

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#14]
please add resistor and diode for PWM aux output

![image](https://user-images.githubusercontent.com/48498823/211674035-d75bdaaf-a5e4-46a1-a917-f44446ccae28.png)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/211923145-2b11991d-5633-4e43-933f-5b8a25737752.png)
