### ISSUE TITLE
hall into oscilloscope

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#16]
let's hook crank and both cams into ADC3 for oscilloscope

we seem to have spare digital inputs to move what is currently digital

**Comment by rusefillc** [comment]
just a bit related to https://github.com/rusefi/hellen125honda-issues/issues/16

related to https://github.com/rusefi/hellen154hyundai/issues/82 and https://github.com/rusefi/hellen121nissan-issues/issues/25 and https://github.com/rusefi/rusefi/pull/4885

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/216082729-07434f90-be8f-404b-a094-473d3b056087.png)

**Comment by rusefillc** [comment]
@mck1117 this makes me wonder if we want to combine ADC and trigger input in one pin?

Well, that starts to look like ADC-based trigger input like in hellen81

Unless it's all totally pointless for Hall anyway :)

**Comment by mck1117** [comment]
> this makes me wonder if we want to combine ADC and trigger input in one pin?

wait, are we routing different things here? what is the point?

which thing do we connect to ADC, the raw pin or after the digital input buffer?

> Unless it's all totally pointless for Hall anyway :)

It is pointless for hall, because it's a digital signal.
