### ISSUE TITLE
rev A sleep consumes too much

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#19]
0.080A running

Good news: wake-up by CAN works!

Other news: sleep move consumption 0.057A lower value desired

```
canRxAdd(0x570)
setCalibration("verboseCan", 1)
setCalibration("enableVerboseCanTx", 0)
setCalibration("enableAemXSeries", 0)

function onCanRx(bus, id, dlc, data)
	print('got CAN id=' ..id ..' dlc=' ..dlc)
	mcu_standby()
end

function onTick()
end

```

```
setCalibration("verboseCan", 1)
setCalibration("enableVerboseCanTx", 0)

yourTimer = Timer.new()

function onTick()
	if yourTimer : getElapsedSeconds() > 1 then
		txCan(1, 0x570, 0, { 0 } )
		yourTimer : reset()
	end
end

```

**Comment by rusefillc** [comment]
@Qwerty-OFF says

Нашел проблему с запитыванием WBO от MCU даже когда питание отключено. В текущей конфигурации нельзя одновременно использовать REF3033 из MCU для опорного напряжения WBO при отключенном питании. Чтобы починить нужно отпаять от R630 и установить U603 (можно взять U102 из другой платы-донора).

https://rusefi.com/docs/ibom/hellen125honda-a-ibom.html

![image](https://user-images.githubusercontent.com/48498823/221694714-7566847c-6276-412f-9f93-293095ddb4bc.png)

**Comment by rusefillc** [comment]
R630 removal is a 0.013A win, removal of three LEDs is about 0.002A

baseline ACTIVE (now with EN logic note while LEDs on the left)

![image](https://user-images.githubusercontent.com/48498823/218620622-faabc6d2-32db-4f51-b52d-e075cd87f0e0.png)

baseline SLEEP (note VTS while LED still ON)
![image](https://user-images.githubusercontent.com/48498823/218620703-b472a441-431a-418e-9e41-d5530af33642.png)

first step: removal of two left blue LEDs from power supply 0.001A improvement
![image](https://user-images.githubusercontent.com/48498823/218620774-f73062fa-6c98-4a25-a4f1-8657f107e378.png)

second step R630 removal
![image](https://user-images.githubusercontent.com/48498823/218620844-8e9fc7e2-2d7a-46b7-ad61-415e422f6c4f.png)

third step 3.3v led removal from mm
![image](https://user-images.githubusercontent.com/48498823/218620922-7a64bd2c-7f96-41bb-877c-f93558387d23.png)

**Comment by Qwerty-OFF** [comment]
@rusefillc check 5v in proto area in sleep mode

**Comment by rusefillc** [comment]
@qwerty-off новая плата. выпаял R630

в прото есть 5в

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/221713305-0ffe03b0-cd4b-4eaa-b74f-1840944a7e79.png)

![image](https://user-images.githubusercontent.com/48498823/221713330-38cf217d-d4ba-427e-a8ef-830423b75ef0.png)

**Comment by rusefillc** [comment]
to be continued on any mm-0.3 board
