### ISSUE TITLE
Control VTC as low side

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#2]
Why are both VTC wires routers into ECU? Usually we have low-side into ECU, why breaking the pattern here?

How do we control that solenoid?

![image](https://user-images.githubusercontent.com/48498823/205788311-09a25bbf-26db-44f8-875c-1730c8d873d1.png)

B15 VTEC is clearly high-side why the inconsistency?!

**Comment by mck1117** [comment]
Connect the pin called VTC(+) (B1) to 12v internal to the ECU (like an ETB), and VTC(-) (B23) to the MOSFET/diode like normal.

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/211654118-986e78e5-2be9-4f73-8c33-b6b722ff780d.png)
