### ISSUE TITLE
smoke close to USB connector

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#20]
![WhatsApp Image 2023-02-15 at 11 06 09](https://user-images.githubusercontent.com/48498823/219106238-0dc8b5da-9cbc-49ca-9f51-ae4ee11f74f0.jpg)

**Comment by Qwerty-OFF** [comment]
Я не убрал лишний R309 из output в replace, поэтому так случилось
![image](https://user-images.githubusercontent.com/4116383/219110746-a3c73dff-f27f-4f43-986c-f8d2a050cc93.png)
И поскольку я "удачно" забыл подключить 5V от этого модуля к общим 5V на плате ничего более страшного не сломалось.
На имеющихся платах можно отпаять R309
В rev. b починю
