### ISSUE TITLE
4.9 wire colors right in connector schematics

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#22]
let's mention "red" "green" "while" right on honda PDF

those seem to be somewhat official https://www.wbo2.com/cable/lsuconns.htm
https://github.com/rusefi/rusefi/wiki/FAQ/LSU-4-9-17025hcon.gif

**Comment by Qwerty-OFF** [comment]
<img width="862" alt="image" src="https://user-images.githubusercontent.com/4116383/219867542-a5246e53-7081-4520-a8a6-5c61cc705407.png">
