### ISSUE TITLE
CAN resistor should it be software-configurable?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#23]
I assume we have 120R somewhere for CAN? can we have it configurable for cases of external CAN already having resistors?

**Comment by rusefillc** [comment]
@mck1117 @eldominio what do you think are there use-cases and reasons to have configurable 120R?

**Comment by Qwerty-OFF** [comment]
Now it is always soldered

The easiest way to configure:
![image](https://user-images.githubusercontent.com/4116383/219934692-ceca5c1b-33f6-4d99-8e68-2647c1e85331.png)
Or specify DNP in BOM

**Comment by rusefillc** [comment]
Jumper vibration bad, manual soldering too complex for our customer base.

We definitely want to learn software-defined CAN termination this board seems like a great place to try it

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/221322920-d71ec92c-1471-4e24-b21e-6f4e8fada568.png)
