### ISSUE TITLE
tach does not work

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#25]
Is it high side or low size?

At the moment we have low side

![image](https://user-images.githubusercontent.com/48498823/219686626-7adea0d5-046d-4887-9309-6d1c2e03e725.png)

**Comment by rusefillc** [comment]
Next step to try high-side control

**Comment by Qwerty-OFF** [comment]
Делаю high-side в rev. b?

**Comment by rusefillc** [comment]
пока нет, попробую во вторник-среду всё-таки подствердить

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/222763124-dfe2f0cc-79e9-4fc4-ac59-9508d837c726.png)

![image](https://user-images.githubusercontent.com/48498823/222763247-e4febc61-ea05-47f4-b962-ee8b96912c03.png)

![image](https://user-images.githubusercontent.com/48498823/222763384-3fe3660e-e05b-4ac8-b99f-3cac0c0e45b5.png)

![image](https://user-images.githubusercontent.com/48498823/222763463-6fbc9224-d71d-4c04-aa90-3e9907f821ed.png)

**Comment by rusefillc** [comment]
P18 did the trick!

since we use P18 for something do we have digital pins to have second pushpull available as aux?

**Comment by Qwerty-OFF** [comment]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/4116383/222893510-ef518063-e74e-4998-8044-4813db42c0b3.png">
PP2 (OUT_IO10) is tacho now. P18 not changed

**Comment by rusefillc** [comment]
let's please remove todo

![image](https://user-images.githubusercontent.com/48498823/222917095-5aca1585-455e-46a7-b88c-0208295c1c19.png)

**Comment by Qwerty-OFF** [comment]
Done
