### ISSUE TITLE
rev A does not read K-line bytes

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#27]
We claim to have HW and SW yet no bytes have arrived so far

https://github.com/rusefi/rusefi/issues/3248

![image](https://user-images.githubusercontent.com/48498823/219815165-114d06de-4b1c-4e08-902d-771a45e24d19.png)

![image](https://user-images.githubusercontent.com/48498823/219815482-7bed1efb-e702-4738-90d7-8eed1d0be52d.png)

![image](https://user-images.githubusercontent.com/48498823/219815187-0e7402c7-bdea-4d58-aef7-bd3708002719.png)

![image](https://user-images.githubusercontent.com/48498823/219815195-24651438-2fcf-4bbd-b400-d9595e7874ca.png)

**Comment by rusefillc** [comment]
I've soldered wires to RX and TX pins of U440 and oscilloscope was showing nothing

I've poked DMM into pin2 and saw 5v as expected?

I've poked DMM into pin3 and saw 12v as expected?

I've then shorted pin3 to pin4 by accident and this board is no longer blinking with stm32 I assume this stm32 is now dead after 12v on UART TX? i have more boards please double check LIN module schematics @Qwerty-OFF @andreika-git

![image](https://user-images.githubusercontent.com/48498823/219826454-e4edb09b-1e94-4ebc-b980-58385dd47924.png)

**Comment by andreika-git** [comment]
Maybe we don't set efiSetPadMode() for UART2?

**Comment by rusefillc** [comment]
@andreika-git says to remove R440

https://github.com/andreika-git/hellen-one/issues/260

**Comment by rusefillc** [comment]
https://www.nxp.com/docs/en/data-sheet/TJA1021.pdf

![image](https://user-images.githubusercontent.com/48498823/219884646-a0e22a24-d869-437c-a14d-8d10a1b89ab5.png)

**Comment by rusefillc** [comment]
got hardware progress, software still unhappy

https://github.com/andreika-git/hellen-one/issues/261

![image](https://user-images.githubusercontent.com/48498823/219900242-d4ea4b20-e706-40b8-98cf-6ca81f613107.png)

**Comment by rusefillc** [comment]
Fun experiment

discovery board happy at 9600
![image](https://user-images.githubusercontent.com/48498823/219972255-56ede224-2ddf-40fc-af94-7d3d0618556f.png)

![image](https://user-images.githubusercontent.com/48498823/219972259-0592c9e4-1aed-4bc5-a11a-880d6d1bafc2.png)

**Comment by rusefillc** [comment]
happy 14400

![image](https://user-images.githubusercontent.com/48498823/219972303-25e74050-586b-45a6-bc39-d9a5c8c0b372.png)
![image](https://user-images.githubusercontent.com/48498823/219972314-0533f285-a7c7-40e3-89e3-45f802cc00b4.png)

**Comment by rusefillc** [comment]
unhappy 10400

![image](https://user-images.githubusercontent.com/48498823/219972346-4e7fbf83-3106-4934-b7f6-31cbeb89e239.png)
![image](https://user-images.githubusercontent.com/48498823/219972355-1b91e6b3-e4ff-40b5-8d32-05e47566c565.png)

**Comment by rusefillc** [comment]
https://rusefi.com/forum/viewtopic.php?p=47201#p47201

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/pull/5125

![image](https://user-images.githubusercontent.com/48498823/221072428-cc3ca100-885b-4dce-bc0c-51cb7aa579a5.png)
