### ISSUE TITLE
SD card status unclear

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#28]
SD card does not show as MSD

could be https://github.com/rusefi/rusefi/issues/5097

**Comment by rusefillc** [comment]
* something is not great with board PDF - search for "SD_CS" does not find me SD_CS text
when I search for MOSI at least I see SD_MOSI but I only see it once, how do I know where is SD card connected to?!

Overall at the moment both mm-01 and mm-02 I have not seen SD card working. What is SD_CS pin just to confirm @Qwerty-OFF ?

![image](https://user-images.githubusercontent.com/48498823/219908709-407514bd-67ed-412f-84cc-8204166ca254.png)

**Comment by Qwerty-OFF** [comment]
Use SPI1 with PB6 CS

**Comment by rusefillc** [comment]
@Qwerty-OFF where can I see this on the PDF?

**Comment by rusefillc** [comment]
just changed to SPI1 and still does not work
```
2023-02-19_13_49_52_243: EngineState: pin PB3: SPI clock
2023-02-19_13_49_52_247: EngineState: pin PB4: SPI master in 
2023-02-19_13_49_52_248: EngineState: pin PB5: SPI master out
2023-02-19_13_49_52_249: EngineState: pin PB6: SD CS
```

![image](https://user-images.githubusercontent.com/48498823/219968862-af87ae6e-c5d8-4920-b438-c8d29b8e9abf.png)

**Comment by rusefillc** [comment]
PDF search issue starts at hellen-one/modules/mega-mcu144/0.2/mega-mcu144-schematic.pdf

if I search for "_mosi" it gives me ACC_MOSE spi1_mosi  spi2_mosi spi3_mosi but nothing about SD

**Comment by rusefillc** [comment]
Good news SD card lines are going at least somewhere :)

![image](https://user-images.githubusercontent.com/48498823/219969608-3ff336a9-d420-4d50-901a-32ca6cc79a94.png)

**Comment by andreika-git** [comment]
We had an external hardware pull-up on SPI1-MOSI because sometimes we needed +5V compatibility and enabled software OPEN-DRAIN mode on MOSI pin:

mcu144:

![image](https://user-images.githubusercontent.com/15104768/221281093-ed52d109-ee61-4e76-8302-6d24e10faf5b.png)

**Comment by rusefillc** [comment]
2chan
![image](https://user-images.githubusercontent.com/48498823/221425013-4b824d1c-a3a9-4ed4-a3fb-2c2f6b0b7feb.png)

**Comment by dron0gus** [comment]
~~"I'm not going to have per-board board.c file."~~
All f4 boards use some random board.c file from STM F4 Discovery board https://github.com/rusefi/rusefi/blob/d1e35213c66ddfc15cd502b980102abe0b2af917/firmware/hw_layer/ports/stm32/stm32f4/hw_ports.mk#L11
`__early_init()` is also used from this file. It calls `stm32_gpio_init()` that is again Discovery-board-specific.
This function set PA5, PA6, PA7 for SPI1 function.
Does any other code reset SPI1 function for these pins before setting PB3, PB4, PB5?

**Comment by rusefillc** [comment]
@dron0gus same nothing :(

![image](https://user-images.githubusercontent.com/48498823/221429031-afd71769-dc66-4e56-a5a6-76714bd8c84c.png)
