### ISSUE TITLE
4 wire DENSO wbo

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#3]
We shall provision for OEM 4 wire middle band sensor control via https://github.com/mck1117/denso-wideband

![image](https://user-images.githubusercontent.com/48498823/208330754-bdb55363-d501-4b20-a5bc-9e2e2f962f62.png)

**Comment by rusefillc** [comment]
@Qwerty-OFF should https://github.com/mck1117/denso-wideband become a hellen module probably?

**Comment by rusefillc** [comment]
EU PRA
![image](https://user-images.githubusercontent.com/48498823/211424578-472e1fff-5b45-4a39-b251-7e3939b38a6d.png)


US PRB
![image](https://user-images.githubusercontent.com/48498823/211424528-99d793b6-db1c-46a1-abf4-7a7def38a274.png)

**Comment by Qwerty-OFF** [comment]
Если мы не будем часто этим пользоваться давай соберу из компонентов, не будем делать лишний модуль.

**Comment by rusefillc** [comment]
Ок, давай пока так!

**Comment by Qwerty-OFF** [comment]
Нагревателем должен управлять контроллер через VND10? Измерение должно производится с контактов A6 и A16 в одном случае, в другом с A6 и E4? Или A16 и E4 должны быть заземлены?

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/212136129-d17ffc5f-ee33-4e6c-a086-e819f5a17526.png)

https://github.com/rusefi/rusefi_documentation/blob/master/OEM-Docs/Honda/2005-rsx-s-1.png

yes A1 heater with VND10

A6 is "positive" and A16 is "negative" signal wires for "4 wire denso" module

A16 not ground

We only care about primary sensor for now so E2 and E4 are just vias.

**Comment by Qwerty-OFF** [comment]
Done
