### ISSUE TITLE
So many k-lines! E24 is the important one let's label it "SEFMJ"

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#30]
Looks like it could be three separate K-lines

E23 should be labeled OBD k-line and only a test pad
E24 should be labeled SEFMJ and connected to LIN module via a jumper
E27 should be labeled immo k-line and only a test pad

![image](https://user-images.githubusercontent.com/48498823/222864709-75a22843-ed07-4e59-af0d-06e462f30482.png)

**Comment by Qwerty-OFF** [comment]
Need to connect E24 to lin module?

**Comment by rusefillc** [comment]
> Need to connect E24 to lin module?

yes, sound like we shall. with a jumper.

**Comment by rusefillc** [comment]
обновил/уточнил тело тикета

**Comment by Qwerty-OFF** [comment]
![Uploading image.png…]()
