### ISSUE TITLE
lin rx/tx let's add jumpers

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#31]
let's add 0R jumpers just on case

![image](https://user-images.githubusercontent.com/48498823/222865081-05dba20f-1c4a-43dc-999c-3f5afcadaa3d.png)

**Comment by Qwerty-OFF** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/4116383/222892209-c3ffa17f-737b-4648-a7ea-09bc4f4ed5b7.png">
