### ISSUE TITLE
Did we add that RX pull-up?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#32]
Do we need a pull-on on RX line?

![image](https://user-images.githubusercontent.com/48498823/222865426-449fc25a-4c82-41aa-8bea-1251fd3c6f50.png)

**Comment by Qwerty-OFF** [comment]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/4116383/222891967-a603d8be-21b0-4ad6-8226-b6e8fc765e0f.png">

**Comment by rusefillc** [comment]
@Qwerty-OFF do we want to increase R92 value?

**Comment by Qwerty-OFF** [comment]
> do we want to increase R92 value?

4.7k now
