### ISSUE TITLE
we have space for nice GND test pad on top of the board

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#35]
maybe somewhere on the side?

**Comment by Qwerty-OFF** [comment]
Is GND pad in power module bad?

**Comment by rusefillc** [comment]
i do not see it. is it the via in the corner marked with G?

**Comment by Qwerty-OFF** [comment]
Yes. Need to add another one?

**Comment by rusefillc** [comment]
Just add "GND" silk angled 45 degrees outside of G via outside of power module rectangle? On both sides of PCB?

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/232162408-c8ce9ca9-0ed1-435c-99a1-4c1af9ecfe49.png)
