### ISSUE TITLE
JDM fuel pump control

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#4]
европа америка на e1

Pin E10 только в японских моделях civic\integra используется для Puel Pump relay

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/211429780-47c7a2db-48ec-416e-9697-85eb03512408.png)

**Comment by Qwerty-OFF** [comment]
Не устанавливать какой-то из джамперов по умолчанию, или оставить оба?

**Comment by rusefillc** [comment]
не устанавливать E10
