### ISSUE TITLE
alternator

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#7]
![image](https://user-images.githubusercontent.com/48498823/211431162-877f2f99-7855-416f-9b74-6b30e0de90e1.png)

reminds me of Hellen72 NB2 miata - that's the only other board where we had alternator control success

https://github.com/rusefi/rusefi_documentation/blob/master/Hardware/Hellen/hellen72-d-schematic.pdf

**Comment by rusefillc** [comment]
нам НАДО: В18 ALTC - это управление генератором с мозга МИНУСОМ. ВОобще сделано для экономии топлива на круизах, при подаче минуса генератор ограничивается до 12.5-13в.

просто via: В13 ALTFR - Это выход нагрузки.  он стандартный на многих генераторах всех машин, передает по своему протоколу значение нагрузки на генер. точно не знаю что именно но пишут 0-5v в зависимости от нагрузки

В10 - ALTL - тут интересно. вообще это просто лампа. и там на заглушенную приходит 0, на заведенную 12в. в хондах старых на приборке на лампе генера 12в всегда висит, и тут уже может от мозга\модели авто зависесть, есть ли такой выход и нужен ли он в  мозгах.

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/211432979-3f250149-7212-422a-bf94-003ba4b49875.png)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/211655879-fd5d502c-a8d9-4043-af96-e0940b75e695.png)
![image](https://user-images.githubusercontent.com/4116383/211655896-6b59ace9-3867-4ee0-9384-d3ffc3f9d171.png)
![image](https://user-images.githubusercontent.com/4116383/211655985-4e62cf3f-c805-4728-9c12-e1300c8370e4.png)

**Comment by rusefillc** [comment]
B10 might be an INPUT of alternator error light which goes to dash?!

it's confusing and probably not important, let's DNP corresponding resistor

**Comment by rusefillc** [comment]
@Qwerty-OFF let's make B10 just a via. no need for B10 output, it's really an input

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/211921199-7c4e499a-b7ec-43a8-85d0-f9d58965a953.png)
