### ISSUE TITLE
A8 intake runner position

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#8]
@Qwerty-OFF definitely please add a resistor

Tommy is that a switch or analog position? Do we even care for A8 input?

**Comment by rusefillc** [comment]
Tommy do we care about that intake runner control from pin B22?

**Comment by rusefillc** [comment]
![image](https://user-images.githubusercontent.com/48498823/211588606-cc885e8d-ed66-40e3-b273-7ff4b2885a81.png)

**Comment by Qwerty-OFF** [comment]
What resistor?

**Comment by rusefillc** [comment]
500K pull-down?
