### ISSUE TITLE
LSU H- should be a wire

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen125honda-issues#9]
We have a six wire sensor, we need to make a six wire harness for it

![image](https://user-images.githubusercontent.com/48498823/211664874-f6b0f04d-4fef-44a3-8b55-6b9b23cb77e6.png)

**Comment by rusefillc** [comment]
OMG https://github.com/andreika-git/hellen-one/issues/251 :(

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/213298070-44f1d256-9737-4957-8c2b-312f5de14506.png)
